@startuml

|Пациент|
start
:Обращение на стойку Администратора 
или звонок на контактный телефон клиники;

|#APPLICATION|Администратор|
if (Администратор свободен?) then (да)
else (нет)
 |Пациент|
  if (Готов ли ждать пациент своей очереди?) then (да)
  else (нет)
   end;
  endif;
  :ожидание своей очереди;
 if (Дождался своей очереди?) then (да)
  :Запрос на медицинские услуги;
 else (нет) 
  end;
 endif;
endif;

|Администратор|
repeat
 :Определение перечня услуг, их доступности и исполнителей. 
согласно запросу пациента;

if (Перечень доступных услуг (их дата/время, состав, последовательность) и
 исполнителей полностью соответствует запросу) then (да)
 :Определение стоимости услуг;
 |Пациент|
 if (Стоимость услуг устраивает?) then (да)
  |Администратор|
  :Регистрация согласованного перечня услуг в журнале;
  stop
 |Пациент|
 else (нет)  
  if (Новый запрос на медицинские услуги?) then (да)
  else (нет)
   end;
  endif;
 endif;
 else (нет)
  if (Новый запрос на медицинские услуги?) then (да)
  else (нет)
   end;
  endif;
 |Администратор|
endif;

repeat while (Получен новый запрос на медицинские услуги) is (да)

@enduml