@startuml

|Пациент|
start
:Запрос на медицинские услуги через интерфрейс 
сайта или мобильного приложения;

|#APPLICATION|Система|
repeat
 :Определение перечня услуг и исполнителей 
 согласно запросу пациента;
 |Пациент|
if (Перечень доступных услуг соответствует запросу) then (да)
 :Выбор услуг из найденного перечня;
 |Система|
 :Определение стоимости услуг;
 |Пациент|
 if (Перечень и стоимость услуг устраивает?) then (да)
  |Система|
  :Регистрация перечня выбранных услуг в базе данных;
  :Уведомление пользователя о произведенной записи согласно 
настройкам по способу и времени доставки уведомлений;
  |Пациент|
  if (Нужен дополнительный поиск в системе?) then (да)
  else (нет)
  stop
  endif;
 |Пациент|
 else (нет)  
  if (Новый запрос на медицинские услуги?) then (да)
  else (нет)
   end;
  endif;
 endif;
 else (нет)
  if (Новый запрос на медицинские услуги?) then (да)
  else (нет)
   end;
  endif;
 |Система|
endif;

repeat while (Получен новый запрос на медицинские услуги) is (да)

@enduml